#!/usr/bin/env python3
"""Generate contribution materials (Issue/PR templates) for arxiv papers."""

from __future__ import annotations

import argparse
import json
import sys
from datetime import datetime
from pathlib import Path

from arxiv_engine.core.utils import find_project, load_info


def generate_issue(project_dir: Path, info: dict) -> Path:
    """Generate Issue template."""
    contribution_dir = project_dir / "contribution"
    contribution_dir.mkdir(exist_ok=True)

    repro_file = project_dir / "REPRODUCTION.md"
    repro_content = repro_file.read_text() if repro_file.exists() else ""

    env_section = ""
    if "## Environment" in repro_content:
        start = repro_content.find("## Environment")
        end = repro_content.find("##", start + 1)
        env_section = repro_content[start:end] if end > 0 else repro_content[start:]

    repo = info.get("github_repo", "owner/repo")
    repo_name = repo.split("/")[-1] if repo else "repo"

    issue_content = (
        f"# Reproduction Issue: {info.get('title', 'Paper Title')}\n\n"
        f"**Paper**: [{info.get('id', 'arXiv ID')}]({info.get('abs_url', '')})\n"
        f"**Repository**: {repo}\n\n"
        f"{env_section}\n\n"
        f"## Steps to Reproduce\n\n"
        f"1. Clone repository\n```bash\ngit clone https://github.com/{repo}.git\ncd {repo_name}\n```\n\n"
        f"2. Install dependencies\n```bash\npip install -r requirements.txt\n```\n\n"
        f"3. Run inference\n```bash\n# Command that fails\n```\n\n"
        f"## Expected Behavior\n\n## Actual Behavior\n\n## Error Log\n```\n```\n\n"
        f"---\n*Generated by arxiv-researcher on {datetime.now().strftime('%Y-%m-%d')}*\n"
    )

    issue_file = contribution_dir / "ISSUE.md"
    issue_file.write_text(issue_content)
    return issue_file


def generate_pr(project_dir: Path, info: dict) -> Path:
    """Generate PR template."""
    contribution_dir = project_dir / "contribution"
    contribution_dir.mkdir(exist_ok=True)

    pr_content = (
        f"# Pull Request: Fix for {info.get('title', 'Paper Title')[:50]}\n\n"
        f"## Summary\n\n"
        f"This PR addresses issues encountered while reproducing the paper "
        f"[{info.get('id', 'arXiv ID')}]({info.get('abs_url', '')}).\n\n"
        f"## Changes Made\n\n- [ ] Bug fix\n- [ ] Environment compatibility\n"
        f"- [ ] Documentation improvement\n- [ ] Code cleanup\n\n"
        f"## Details\n\n### Problem\n\n### Solution\n\n"
        f"## Testing\n\n```bash\npython inference.py --input sample.jpg\n```\n\n"
        f"## Checklist\n\n- [ ] Code follows project style\n- [ ] Tests pass locally\n"
        f"- [ ] Changes are minimal and focused\n\n"
        f"---\n*Generated by arxiv-researcher on {datetime.now().strftime('%Y-%m-%d')}*\n"
    )

    pr_file = contribution_dir / "PR.md"
    pr_file.write_text(pr_content)
    return pr_file


def generate_blog(project_dir: Path, info: dict) -> Path:
    """Generate blog post template from SUMMARY.md and REPRODUCTION.md."""
    contribution_dir = project_dir / "contribution"
    contribution_dir.mkdir(exist_ok=True)

    summary_file = project_dir / "SUMMARY.md"
    summary_content = summary_file.read_text() if summary_file.exists() else ""

    gh_url = f"https://github.com/{info.get('github_repo')}" if info.get("github_repo") else "N/A"

    blog_content = (
        f'# Reproducing "{info.get("title", "Paper Title")[:60]}"\n\n'
        f"**Paper**: [{info.get('id', 'arXiv ID')}]({info.get('abs_url', '')})\n"
        f"**Code**: [{gh_url}]({gh_url})\n"
        f"**Date**: {datetime.now().strftime('%Y-%m-%d')}\n\n"
        f"## TL;DR\n\n## Paper Overview\n\n"
        f"{summary_content if summary_content else '<!-- Add paper summary here -->'}\n\n"
        f"## Reproduction Journey\n\n### Setup\n\n### Key Findings\n\n"
        f"### Performance Results\n\n"
        f"| Metric | Paper | Reproduced | Difference |\n"
        f"|--------|-------|------------|------------|\n\n"
        f"## Lessons Learned\n\n## Code Snippets\n\n```python\n```\n\n"
        f"## Conclusion\n\n"
        f"---\n*Created with arxiv-researcher.*\n"
    )

    blog_file = contribution_dir / "BLOG.md"
    blog_file.write_text(blog_content)
    return blog_file


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate contribution materials")
    parser.add_argument("type", choices=["issue", "pr", "blog", "all"],
                        help="Type of material to generate")
    parser.add_argument("id", nargs="?", help="arXiv ID (uses context if omitted)")
    parser.add_argument("--json", "-j", action="store_true", help="JSON output")
    args = parser.parse_args()

    project_dir = find_project(args.id)
    if project_dir is None:
        print("No project found. Specify ID or set context first.")
        sys.exit(1)

    print(f"Project: {project_dir.name}")

    info = load_info(project_dir)
    generated = []

    if args.type in ("issue", "all"):
        generated.append(("Issue", generate_issue(project_dir, info)))
    if args.type in ("pr", "all"):
        generated.append(("PR", generate_pr(project_dir, info)))
    if args.type in ("blog", "all"):
        generated.append(("Blog", generate_blog(project_dir, info)))

    for label, path in generated:
        print(f"Generated {label}: {path}")

    if args.json:
        print(json.dumps([{"type": t, "path": str(p)} for t, p in generated], indent=2))
    else:
        print(f"\nFiles ready in: {project_dir / 'contribution'}")


if __name__ == "__main__":
    main()
