#!/usr/bin/env python3
"""Generate contribution materials (Issue/PR templates) for arxiv papers."""

import argparse
import json
import sys
from datetime import datetime
from pathlib import Path

# Add local directory to path to import utils
sys.path.append(str(Path(__file__).parent))
from utils import find_project, load_info

SKILL_DIR = Path(__file__).parent.parent


def generate_issue(project_dir: Path, info: dict) -> Path:
    """Generate Issue template."""
    contribution_dir = project_dir / "contribution"
    contribution_dir.mkdir(exist_ok=True)

    # Read REPRODUCTION.md for context
    repro_file = project_dir / "REPRODUCTION.md"
    repro_content = repro_file.read_text() if repro_file.exists() else ""

    # Extract environment section
    env_section = ""
    if "## Environment" in repro_content:
        start = repro_content.find("## Environment")
        end = repro_content.find("##", start + 1)
        env_section = repro_content[start:end] if end > 0 else repro_content[start:]

    issue_content = f"""# Reproduction Issue: {info.get('title', 'Paper Title')}

**Paper**: [{info.get('id', 'arXiv ID')}]({info.get('abs_url', '')})
**Repository**: {info.get('github_repo', 'Not specified')}

{env_section}

## Steps to Reproduce

1. Clone repository
```bash
git clone https://github.com/{info.get('github_repo', 'owner/repo')}.git
cd {info.get('github_repo', 'repo').split('/')[-1] if info.get('github_repo') else 'repo'}
```

2. Install dependencies
```bash
pip install -r requirements.txt
```

3. Run inference
```bash
# Command that fails
```

## Expected Behavior
<!-- What should happen according to the paper/README -->

## Actual Behavior
<!-- What actually happens -->

## Error Log
```
# Paste full error traceback here
```

## Additional Context
- Attempting to reproduce results from the paper
- Following README instructions

---
*Generated by arxiv-researcher on {datetime.now().strftime('%Y-%m-%d')}*
"""

    issue_file = contribution_dir / "ISSUE.md"
    issue_file.write_text(issue_content)
    return issue_file


def generate_pr(project_dir: Path, info: dict) -> Path:
    """Generate PR template."""
    contribution_dir = project_dir / "contribution"
    contribution_dir.mkdir(exist_ok=True)

    pr_content = f"""# Pull Request: Fix for {info.get('title', 'Paper Title')[:50]}

## Summary

This PR addresses issues encountered while reproducing the paper [{info.get('id', 'arXiv ID')}]({info.get('abs_url', '')}).

## Changes Made

- [ ] Bug fix
- [ ] Environment compatibility (e.g., newer PyTorch/CUDA)
- [ ] Documentation improvement
- [ ] Code cleanup

## Details

### Problem
<!-- What problem does this PR solve? -->

### Solution
<!-- How does this PR solve it? -->

## Testing

```bash
# Commands to test the changes
python inference.py --input sample.jpg
```

### Test Results
```
# Paste test output showing the fix works
```

## Environment
- OS:
- Python:
- PyTorch:
- CUDA:

## Checklist

- [ ] Code follows project style
- [ ] Tests pass locally
- [ ] Changes are minimal and focused
- [ ] No breaking changes

---
*Generated by arxiv-researcher on {datetime.now().strftime('%Y-%m-%d')}*
"""

    pr_file = contribution_dir / "PR.md"
    pr_file.write_text(pr_content)
    return pr_file


def generate_blog(project_dir: Path, info: dict) -> Path:
    """Generate blog post template from SUMMARY.md and REPRODUCTION.md."""
    contribution_dir = project_dir / "contribution"
    contribution_dir.mkdir(exist_ok=True)

    # Read existing files
    summary_file = project_dir / "SUMMARY.md"
    repro_file = project_dir / "REPRODUCTION.md"

    summary_content = summary_file.read_text() if summary_file.exists() else ""
    repro_content = repro_file.read_text() if repro_file.exists() else ""

    blog_content = f"""# Reproducing "{info.get('title', 'Paper Title')[:60]}"

**Paper**: [{info.get('id', 'arXiv ID')}]({info.get('abs_url', '')})
**Code**: [GitHub]({f"https://github.com/{info.get('github_repo')}" if info.get('github_repo') else 'N/A'})
**Date**: {datetime.now().strftime('%Y-%m-%d')}

## TL;DR

<!-- One paragraph summary of the paper and reproduction experience -->

## Paper Overview

{summary_content if summary_content else '<!-- Add paper summary here -->'}

## Reproduction Journey

### Setup

<!-- Describe environment setup, any issues encountered -->

### Key Findings

<!-- What worked, what didn't, deviations from paper -->

### Performance Results

| Metric | Paper | Reproduced | Difference |
|--------|-------|------------|------------|
| Accuracy | - | - | - |
| Latency | - | - | - |

## Lessons Learned

<!-- Key takeaways for others attempting reproduction -->

## Code Snippets

```python
# Key implementation details
```

## Conclusion

<!-- Final thoughts, recommendations -->

---

*This post was created as part of my paper reproduction workflow using arxiv-researcher.*
"""

    blog_file = contribution_dir / "BLOG.md"
    blog_file.write_text(blog_content)
    return blog_file


def main():
    parser = argparse.ArgumentParser(description="Generate contribution materials")
    parser.add_argument("type", choices=["issue", "pr", "blog", "all"],
                        help="Type of material to generate")
    parser.add_argument("id", nargs="?", help="arXiv ID (uses context if omitted)")
    parser.add_argument("--json", "-j", action="store_true", help="JSON output")
    args = parser.parse_args()

    project_dir = find_project(args.id)
    if project_dir is None:
        print("❌ No project found. Specify ID or set context first.")
        sys.exit(1)

    print(f"📁 Project: {project_dir.name}")

    info = load_info(project_dir)
    generated = []

    if args.type in ["issue", "all"]:
        issue_file = generate_issue(project_dir, info)
        generated.append(("Issue", issue_file))
        print(f"✅ Generated: {issue_file}")

    if args.type in ["pr", "all"]:
        pr_file = generate_pr(project_dir, info)
        generated.append(("PR", pr_file))
        print(f"✅ Generated: {pr_file}")

    if args.type in ["blog", "all"]:
        blog_file = generate_blog(project_dir, info)
        generated.append(("Blog", blog_file))
        print(f"✅ Generated: {blog_file}")

    if args.json:
        print(json.dumps([{"type": t, "path": str(p)} for t, p in generated], indent=2))
    else:
        print(f"\n📝 Files ready in: {project_dir / 'contribution'}")


if __name__ == "__main__":
    main()
